andes/andesMicroservices

pecas-integration/controller/export-data.ts
Se agrega la query para almacenar en logs
=> hot fix log query insert

pecas-integration/controller/export-data.ts, pecas-integration/index.ts
Se agrega a los logs la posibilidad de visualizar cual es la query que se ejecuta.
=> Se hace un fix en la operacion de logs y en la conexion bd logs

pecas-integration/controller/export-data.ts, pecas-integration/index.ts, pecas-integration/package-lock.json
* Mejora en el microservicio de PECAS
1. Se agregaron condiciones para el procesamiento de la agenda
2. Se agrego control para los efectores que no tengan cargado código SIPS
=> Controles pecas

package-lock.json, package.json, pecas-integration/controller/export-data.ts, pecas-integration/index.ts, pecas-integration/package-lock.json, pecas-integration/package.json
=> Pecas queued

pecas-integration/controller/export-data.ts
* Se corrige INSERT para que castee caracteres extraños
=> BI - Fix caracteres en insert 

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts, cda-laboratorios/index.ts, cda-laboratorios/package-lock.json, cda-laboratorios/package.json, package-lock.json, package.json
1.  Implemanta cola de tareas para no saturar el servicio.
2. Cache de request de organizaciones.
3. Handler de error en request de pdf. (Queda log momentaneo para probar).
=> cda-laboratorios: mejoras

cda-nomivac/controller/sisa.ts, cda-nomivac/index.ts
1. Quita paciente Fhir dado que del webhook, por ahora, no se estaría realizando la conversión. 
2. Agrega el establecimiento de aplicación de la vacuna al texto del cda
3.
=> Agrega el efector a los cdas de vacunas

facturacion/configJson/configJson.ts, facturacion/factura.ts, facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/recupero-financiero/query-recupero.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/facturar/sumar/query-sumar.ts, facturacion/index.ts, facturacion/interfaces/IDtoFacturacion.ts, facturacion/interfaces/IDtoRecupero.ts, facturacion/interfaces/IDtoSumar.ts, facturacion/package-lock.json, facturacion/package.json, facturacion/schemas/config-prestaciones.ts
Funcionalidad desarrollada:
1- Se creó in microservicio para poder facturar automáticamente prestaciones de Recupero Financiero y Sumar.
Agregar webhook facturacion:factura:create
=> Facturacion

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts, cda-laboratorios/index.ts
* Se detencto un bug en el webservice que incluía blancos en la url del pdf, evitando obtener estudios.
* Se cambió la librería http (deprecated) por la que estamos usando actualmente (request).
=> Laboratorios: Cambiamos a libreria request y solucionamos bug webservice HHH

paciente_sumarYsips/controller/consultas.ts, paciente_sumarYsips/controller/ejecutaConsulta.ts, paciente_sumarYsips/index.ts, paciente_sumarYsips/package-lock.json, paciente_sumarYsips/package.json, paciente_sumarYsips/service/operaciones.service.ts
* https://pm.andes.gob.ar/projects/andes/work_packages/654/activity
1. Se retomo el microservicio para insertar pacientes en Sips y sumar.
2. Se hizo refactor de código ya que se pensó mejor como venia el paciente desde la api.
3. Se hicieron los updates que habian quedado pendientes
4. Crea/actualiza registros en sys_paciente, pn_beneficiario, sys_parentezco
=> Microservicio para tablas de SIPS y SUMAR- Version 2

paciente_sumarYsips/controller/consultas.ts
1. Le agrego el objectId de ANDES al actualizar sips para mejor seguimiento
=> Paciente sips y sumar

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/facturar/sumar/query-sumar.ts, facturacion/index.ts, facturacion/interfaces/IDtoFacturacion.ts, facturacion/interfaces/IDtoSumar.ts, facturacion/services/config-factAutomatica.service.ts, facturacion/services/obra-social.service.ts, facturacion/services/organizacion.service.ts, facturacion/services/prestaciones.service.ts, facturacion/services/profesional.service.ts, facturacion/services/snomed.service.ts
1. Se corrige la fecha de prestación del turno. Se pone la fecha del turno en fecha de prestación en Sumar
=> Se corrige fecha de prestación en Sumar

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/facturar/sumar/query-sumar.ts
1.  Se valida los datos reportables vacíos en niño sano en sumar.
2. Se corrige formato de fecha en Fecha de Prestación Sumar
=> Se valida datos reportables en niño sano

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/services/config-factAutomatica.service.ts
1. Se validan las prestaciones de Sumar que no tienen datos reportables para poder generar el comprobante.
=> Se validan prestaciones sin DR en Sumar

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/index.ts, facturacion/package.json, facturacion/services/prestaciones.service.ts
Actualizar los datos reportables para niño sano
1- Se corrige el patch para estado facturación en prestaciones fuera de agenda
2- Se refactoriza la búsqueda en huds de paciente para la prestación niño sano
=> Acutalización v4.4.12

facturacion/facturar/dto-facturacion.ts
1. Se corrige la validación de los datos de configuración en sumar
=> Se corrige validación de coleccion de configuración

facturacion/facturar/dto-facturacion.ts, facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/recupero-financiero/query-recupero.ts, facturacion/facturar/sumar/query-sumar.ts, facturacion/index.ts
1. Se pasan menos parámetros al log de Andes
=> Se pasan menos parámetros al andes log

cda-validator/constantes.ts, cda-validator/controller/queries/junin.ts
* Habilitar el histórico del Hospital de Junin de los Andes
1. Agregar la conexión y consulta para habilitar el histórico del Hospital de Junin de los Andes
=> CDAS - Historico junin

appGestion/controller/recuperaDatos.ts, appGestion/index.ts, appGestion/package.json
* Servicio para migrar datos de servidor sips en la app mobile
Pedir config.private
=> Microservicio - Servicio para migrar datos en app mobile

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/facturar/sumar/query-sumar.ts
* Agregar control para que los datos reportables estén completos. Agregar Paciente en la tabla PN_Beneficiario
* 
1. Agregar control para que los datos reportables estén completos
2. Se crea un paciente en la tabla PN_Beneficiario en el caso de que el mismo no se encuentra en Puco, en la tabla de Afiliados Sumar y en la tabla de Beneficiarios Sumar.
=> Facturación - Control datos reportables

cda-validator/constantes.ts, cda-validator/controller/queries/centenario.ts
1. Se generan los cda para el hospital Centenario
=> Se generan cda para hospital Centenario

cda-validator/constantes.ts, cda-validator/controller/queries/plottier.ts, cda-validator/controller/queries/zapala.ts
1. Se generan cda de Zapala 
2.  Se generan cda de Plottier
=> Cda zapala plottier

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/recupero-financiero/query-recupero.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/interfaces/IDtoRecupero.ts
1. Se valida formato de TA según DOIU Sumar .
2. Se valida formato talla según DOIU Sumar. 
3. Se validan que los datos reportables cargados en la prestación coincidan con los datos reportables de la colección configAutomatica para cada prestación
4. Se pone la fecha del turno a la fecha de siniestro en RF
=> Validación de datos reportable

facturacion/facturar/dto-facturacion.ts, facturacion/facturar/sumar/query-sumar.ts
1.  La consulta para saber si un paciente tiene la misma prestación el mismo día se pasa a un Stored Procedure llamado [PN_ValidaPrestacionPaciente]
2. En prestaciones de niño sano, si la profesión es distinta de médico se devuelve null
=> Se pasa a Stored Procedure la validación de prestaciones

appGestion/controller/recuperaDatos.ts, appGestion/index.ts, appGestion/service/login.ts
Realizar una tabla intermedia con los campos: Lugar de pago, id efector, id area para que se corresponda con la tabla de los profesionales 
1. Método para migrar datos de profesionales de sips a la app mobile
2. Autenticación del microservicio para que solo se realice la migración de los datos cuando el usuario loguedo es de gestión
=> AppGestion - profesionales

appGestion/index.ts, appGestion/service/login.ts
* El microservicio de la app mobile necesitaba autenticacion
=> Autenticación gestión

facturacion/facturar/sumar/factura-sumar.ts
1. Se setea el período del comprobante según la fecha de la prestación en lugar de la fecha de carga del comprobante.
=> Se setea período de comprobante de acuerdo a la fecha de prestación

cda-validator/constantes.ts, cda-validator/controller/queries/bouquet.ts
1. Se generan los cda para el hospital Bouquet Roldán
=> Se generan cda para bouquet roldán

appGestion/controller/recuperaDatos.ts, appGestion/index.ts
* https://pm.andes.gob.ar/projects/mobile-app/work_packages/845/activity
1. Consulta para obtener datos de mortalidad para luego migrarlos a la mobile-app
Nota: La url de la user story hace referencia al requerimiento desde la mobile-app pero para realizarlo había que antes hacer este servicio.
=> AppGestion: mortalidad

paciente_sumarYsips/controller/consultas.ts, paciente_sumarYsips/controller/ejecutaConsulta.ts, paciente_sumarYsips/index.ts, paciente_sumarYsips/service/operaciones.service.ts
1. Se modifica la inserción de pacientes en Sips 
2. Se modifica la inserción de pacientes en Sumar
3. Se sacan algunas llamadas a la api que no se usan en Sips o Sumar
4. Se comenta la inserción de parentezco en sips para pacientes sin DNI ya que en sips esto no se usa
=> Refactorización microservicio de pacientes Sips y Sumar

appGestion/controller/recuperaDatos.ts
* Se cambio la consulta para recuperar datos nuevos agregados en las bases de datos
1. Select completo
=> App gestion: datos epidemiología

appGestion/controller/recuperaDatos.ts
* Se cambio la consulta para recuperar datos nuevos agregados en las bases de datos
1. Select completo
=> AppGestion: consulta appDatos

paciente_sumarYsips/controller/consultas.ts, paciente_sumarYsips/controller/ejecutaConsulta.ts, paciente_sumarYsips/service/operaciones.service.ts
* Agregar logs para un mayor seguimiento a los microservicios Paciente Sumar_Sips
1. Agrego logs en situaciones de fallo.
2. Elimino logs en situaciones de exito
=> feat (Microservicio: pacienteSumar_Sips):

appGestion/controller/recuperaDatos.ts, appGestion/index.ts
* Se cambio la consulta para recuperar datos nuevos agregados en las bases de datos
1.MIgracion de tabla automotores para la app de gestión
=> AppGestion: migración de automotores

cda-validator/constantes.ts
1. Se generan cda para Rincón de los Sauces. 
2. Se generan cda para Villa la Angostura
```
En config.private pegar estas conexiones:
rincon: {
user: 'sa',
password: 'ssecure',
ip: '10.6.8.16',
database: 'SIntegralH'
},
villa_angostura: {
user: 'sa',
password: 'ssecure',
ip: '10.20.8.19',
database: 'SIntegralH'
}
export let efectores = [..., 'rincon', 'villa_angostura']
```
=> feat(CDA): Se generan cda para Rincón de los Sauces y Villa la Angostura

sms/controller/sms.ts, sms/index.ts, sms/package-lock.json, sms/package.json
=> Microservicios: Aviso por sms a pacientes al sacar turno

bus-federador/config.ts, bus-federador/index.ts, bus-federador/lib/federar.ts, bus-federador/lib/request.ts, bus-federador/lib/salud-digital-cliente.ts, bus-federador/package-lock.json, bus-federador/package.json, bus-federador/tsconfig.json
Se creó un nuevo microservicio para el envío de pacientes al federador Nacional.
1- Creación de token.
2- Envío del paciente en un recurso FHIR.
Requiere la instalación del paquete FHIR versión 2.0.0 
npm i @andes/fhir@next
=> feat(bus-federador): add microservice federador

facturacion/configJson/configJson.ts, facturacion/configJson/datos-reportables.ts, facturacion/factura.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/index.ts, facturacion/services/profesional.service.ts
1. Se detecta el origen de la facturación de acuerdo al webhook disparado.
2. Se saca en un archivo aparte la lógica de los datos reportables
=> refactor(Facturacion Automática): Se corrigen eventos webhook

paciente_sumarYsips/controller/consultas.ts
1.  Se guarda cuie en efector sumar en lugar del id efector
2. Se eliminan los acentos en los Departamentos de Sumar
=> fix(sumar): se guarda cuie en efector Sumar

bi-queries/README.md, bi-queries/controller/csv-stream.ts, bi-queries/controller/mapping-stream.ts, bi-queries/controller/pipeline-builder.ts, bi-queries/controller/queries.controller.ts, bi-queries/controller/sql-exporter.ts, bi-queries/index.ts, bi-queries/package-lock.json, bi-queries/package.json, bi-queries/schemas/query.ts, bi-queries/schemas/query_mapping.ts, bi-queries/tsconfig.json, facturacion/index.ts, package-lock.json, package.json
Módulo para realizar consultas a la Base de Dato
1. GetAllQueries: se obtienen todas las queries de la colección queries.
2. Descargar: Se descarga archivo CSV con resultado de la consulta (si tuviera parámetros previamente deben cargarse)
=> BiQueries: consultas a la BD

bi-queries/controller/sql-exporter.ts, bi-queries/index.ts, bi-queries/schemas/query.ts
Agrega filtro por nombre en la búsqueda de queries.
Agrega campo data en el esquema de queries para los argumentos necesarios para la exportación.
Agrega puerto en la configuración default para exportar
=> fix(bi-queries): Agrega filtro por nombre para querys

bi-queries/index.ts, bi-queries/schemas/query.ts
https://proyectos.andes.gob.ar/browse/BI-40
1. Se agrega _get_ que devuelve los resultados de ejecutar la consulta que ingresa por parámetro con formato _json_.
2. Se agrega a _QuerySchema_ la variable booleana _desdeAndes_ para saber si la query debe ser visible desde Andes.
=> Bi-Queries: Acceso a reportes de covid 19 desde Andes

profesional_sips/controller/consultas.ts, profesional_sips/controller/ejecutaConsulta.ts, profesional_sips/index.ts, profesional_sips/package-lock.json, profesional_sips/package.json, profesional_sips/service/operaciones.service.ts
https://proyectos.andes.gob.ar/browse/IO-3
Se creó un microservicio para dar de alta profesionales en SIPS
###Observaciones
Para probar el mapeo de profesiones con el tipoProfesion de SIPS, hay que sumar a los identificadores de la profesión un objeto con nombre "tipoProfesionalSIPS". Por ejemplo:
{
"_id" : ObjectId("5aa903b07f4f67f88a64c471"),
"código" : 53,
"nombre" : "Médico veterinario",
"tipoDeFormacion" : "Grado Universitario",
"Profesiones" : 1,
"habilitado" : true,
"identificadores" : [ 
{
"entidad" : "SIPS",
"valor" : "5"
}
]
}
=> MICROSERVICIOS: agregar profesional en sips

bi-queries/controller/pipeline-builder.ts
Resuelve bug para query sin argumentos
1. Se agregaron controles para una query con argumentos null o arreglo vacío.
=> BIQueries: cambios para procesar queries sin argumentos

cda-laboratorios/index.ts
* Agrega eventos de creación y actualización de pacientes, para la generación del los cda de laboratorio.  Los eventos mpi:paciente son necesarios para los eventos disparados desde las rutas de core-v2
1. 
2. 
3.
=> fix(cda-laboratorio): agrega eventos de paciente

sms-aws/controller/sms.ts, sms-aws/index.ts, sms-aws/package-lock.json, sms-aws/package.json
* Microservicio que permite el envío de mensajes vía amazon SNS services.
Obs: Solicitar las claves para realizar las prueabas. (a @sychus )
=> feat(sms-aws): Envio de sms usando amazon services

sms-aws/controller/sms.ts
Agregar una variable de entorno para poder setear la región de los servidores de amazon
=> fix(region): Quitamos el hardcodeo de la region y se reemplaza por una environment variable

cda-laboratorio-central/controller/import-labs.ts, cda-laboratorio-central/index.ts
- Soluciona la referencia al objeto paciente, ya que estaba mal referenciado y no entraba nunca cuando se emitia desde un evento de la api.
OBS: Recordar instalar la librería oculta en el servidor, ya que sino no es posible generar los pdf.
OBS2: Revisar en el ecosystem del servidor, porque puede haber problemas con las rutas cuando levanta el process.cwd() !!!
=> fix(index): soluciona referencia a objeto paciente

cda-laboratorio-central/controller/import-labs.ts
Se estaba usando mal moment para la fecha del reporte.
=> fix(cda-laboratorio-central): fix wrong date format

bi-queries/controller/pipeline-builder.ts, bootstrap/index.ts, bootstrap/package-lock.json, bootstrap/package.json
https://proyectos.andes.gob.ar/browse/BI-69
1. Se agrega control del nuevo permiso, en el caso que el usuario tenga permiso para ejecutar las consultas en todas las organizaciones, modifica el campo required de este argumento.
2. Se agrega el plugin express-query-boolean.
=> BI-QUERIES: Campo obligatorio/no obligatorio "organización" en bi queries

cda-nomivac/controller/sisa.ts, cda-nomivac/index.ts, cda-nomivac/package-lock.json, cda-nomivac/package.json, cda-nomivac/service/nomivacWSsisa.ts
https://proyectos.andes.gob.ar/browse/IO-14
1. Reemplaza request para importacion de vacunas
=> Nomivac - Reemplaza peticion sql por api rest de sisa

cda-nomivac/controller/sisa.ts, cda-nomivac/package-lock.json, cda-nomivac/package.json, cda-nomivac/service/nomivacWSsisa.ts
* Actualiza el servicio ws201 con la nueva url: https://apisalud.msal.gob.ar/nomivacWs201/v1/api/sniAplicacion
1. Quita el uso de node-fetch, ya que no permite realizar get con body (se reemplaza por request)
2. Actualiza campos de las vacunas
3.
=> feat(cda-nomivac): actualiza url de ws201

cda-nomivac/controller/sisa.ts
*  La api de consultas de aplicaciones de vacunas cambió el formato de respuesta
1. 
2. 
3.
=> fix(cda-nomivac): Cambia formato de vacunas

cda-nomivac/controller/sisa.ts, cda-nomivac/service/nomivacWSsisa.ts
* Actualiza la api de consultas de vacunas, con los últimos cambios enviados por Nación
1. 
2. 
3.
=> fix(cda-nomivac): actualiza api de nomivac

cda-nomivac/controller/sisa.ts
* Cambia formato de fecha
1. 
2. 
3.
=> fix(cda-nomivac): fix fecha

cda-nomivac/controller/sisa.ts
* Cambia el campo donde viene el número de documento del paciente
1. 
2. 
3.
=> fix(nomivac): Campo documento

package-lock.json, profesional_sisa/controller/ejecutaConsulta.ts, profesional_sisa/index.ts, profesional_sisa/package-lock.json, profesional_sisa/package.json, profesional_sisa/service/operaciones.service.ts
https://proyectos.andes.gob.ar/browse/MAT-42
1. Microservicio para exportar profesionales matriculados a SISA
2. 
3. 
```
{
"_id" : ObjectId("6001de8bfd77a28bcfc6149e"),
"event" : "matriculaciones:profesionales:create",
"url" : "http://172.16.1.82:3014/profesionalSISA",
"method" : "POST",
"active" : true
}
```
=> feat: export profesional SISA

profesional_sisa/package.json
=> fix(profesional_sisa): agrega scripts

sms-aws/controller/sms.ts
https://github.com/andes/api/pull/1338
=> feat(sms-aws): Cambiamos el evento para envío de sms de laboratorio

paciente_sumarYsips/service/operaciones.service.ts
https://proyectos.andes.gob.ar/browse/MPI-305
Cambiar ruta del microservicio paciente_sumarYsips
1. se cambia la ruta en pacientes por la de V2 en el microservicio paciente_sumarYsips
2. 
3.
=> paciente_sumarYsips: Cambio a rutas V2 en pacientes

profesional_sips/controller/consultas.ts
* Agrega control para verificar si el profesional se encuentra matriculado, para obtener el número de matrícula correspondiente
1. 
2. 
3.
=> fix(profesional_sips): corrige error de matricula

sip-plus-perinatal/config.private.example.ts, sip-plus-perinatal/controller/sip-plus.ts, sip-plus-perinatal/index.ts, sip-plus-perinatal/package-lock.json, sip-plus-perinatal/package.json, sip-plus-perinatal/schemas/paciente.ts, sip-plus-perinatal/schemas/perinatal.ts, sip-plus-perinatal/schemas/query_mapping.ts, sip-plus-perinatal/service/matchPerinatal.ts, sip-plus-perinatal/service/paciente.ts, sip-plus-perinatal/service/sip-plus.ts, sip-plus-perinatal/tsconfig.json
Se crea un microservicio que conecta Andes con Sip-plus, registrando datos del paciente en una consulta por control de embarazo.
https://proyectos.andes.gob.ar/browse/PER-3
https://proyectos.andes.gob.ar/browse/PER-4
https://proyectos.andes.gob.ar/browse/PER-5
https://proyectos.andes.gob.ar/browse/PER-17
https://proyectos.andes.gob.ar/browse/PER-24
Al generar una prestacion desde Andes, se registran datos del paciente y su embarazo actual 
1. Se busca al paciente en SIPPlus
2. Si el paciente existe en SIP-Plus se crea o actualizan datos del embarazo registrado en la prestacion
3. Si el paciente no existe en SIP-Plus se crea paciente en SIP
- Agregar en la colección de Webhook:
```
{
"event" : "rup:prestacion:validate",
"url" : "http://localhost:3000/perinatal/register",
"method" : "POST", …
```
=> Nuevo microservicio para conectarse con sip-plus

sip-plus-perinatal/controller/sip-plus.ts
Se agrega control para un registro de control embarazo que es un objeto vacío
1. 
2. 
3.
=> SIPPLUS:fix en mapeo de cada control embarazo

facturacion-perinatal/config.private.example.ts, facturacion-perinatal/controller/perinatal.ts, facturacion-perinatal/index.ts, facturacion-perinatal/package-lock.json, facturacion-perinatal/package.json, facturacion-perinatal/service/organizacion.ts, facturacion-perinatal/service/paciente.ts, facturacion-perinatal/service/queriesSql.ts, facturacion-perinatal/tsconfig.json
https://proyectos.andes.gob.ar/browse/PER-22
Al validar una consulta por "Control de embarazo" se crean o actualizan tuplas en las tablas deSIPSperinatal necesarias para poder facturar a SUMAR. 
1. Insert sobre 3 tablas SIPS perinatal al validar la prestacion
2. update sobre 3 tablas SIPS perinatal al revalidar la prestacion
3. 
Agregar en la colección de Webhook:
{
"event" : "rup:prestacion:validate",
"url" : "http://localhost:3000/perinatalSql/create",
"method" : "POST",
"active" : true
}
=> Perinatal: microservicio de Facturacion - Perinatal

cda-laboratorio-central/controller/operations.ts, cda-laboratorio-central/utils/informes/informe-body.ts
https://proyectos.andes.gob.ar/browse/MISC-170
1. Incluye datos de validación en CDA
2. 
3.
=> MISC: datos validacion CDA Lab Central

cda-laboratorio-central/utils/informes/informe-body.ts, cda-laboratorio-central/utils/sass/main.scss
Corrige visualización de datos de validación en cda de laboratorio central
1. 
2. 
3.
=> MISC: fix datos validacion labcentral

sip-plus-perinatal/index.ts
se asocia al micro-servicio con más prestaciones vinculadas a un control embarazo
1. 
2. 
3.
=> SIP-Plus: se asocia con mas prestaciones

lamp/config.private.example, lamp/controller/lamp.controller.ts, lamp/controller/queries/laboratorio.ts, lamp/index.ts, lamp/package.json, lamp/service/lamp.service.ts
Microservicio importador de lamp
1. Micro servicio que importa resultados de LAMP desde las bases de datos del SIL
2. 
3.
=> EP: Microservice lamp importer

lamp/controller/lamp.controller.ts, lamp/package.json
fix referencia seccion
1. 
2. 
3.
=> LAMP: fix referencia seccion

sip-plus-perinatal/index.ts
Se agrega prestacion "consulta de control de embarazo de alto riesgo" al mapeo de datos
1. 
2. 
3.
=> sip-plus: se agrega prestacion al mapeo

lamp/controller/lamp.controller.ts, lamp/package.json, lamp/service/lamp.service.ts
logs en microservicio de lamp
1. 
2. 
3.
=> LAMP: logs

facturacion-perinatal/index.ts
Se incluyen nuevas prestaciones para enviar datos a SIPS, utilizados en facturación.
1. 
2. 
3. 
- X ] Si
=> facturacion-perinatal: se incluyen nuevas prestaciones

cda-nomivac/controller/sisa.ts
https://proyectos.andes.gob.ar/browse/VAC-90
1. Modifica datos a guardar en nomivac
=> Vac - Refactor de datos para coleccion nomivac

cda-nomivac/controller/sisa.ts
Modifica la variable para tomar el nombre del esquema
1. 
2. 
3.
=> Fix nombre esquema

lamp/controller/lamp.controller.ts
Arregla bug  de documento vacio. Descarta fichas con paciente con documento vacío para no romper la query SQL.
1. 
2. 
3.
=> LAMP: fix documento paciente

lamp/controller/queries/laboratorio.ts, lamp/package.json
Fix para bug de length de query
1. 
2. 
3.
=> EP: fix bug query length

lamp/controller/queries/laboratorio.ts
=> EP: remove self certificate

lamp/controller/lamp.controller.ts, lamp/controller/queries/laboratorio.ts, lamp/package.json
=> EP: chunck array documentos

cda-validator/constantes.ts
Quitar el efector Heller de la configuración para generar Cdas.
1. 
2. 
3.
=> fix: Quitar la configuración de Heller para consultar cdas

cda-laboratorios/controller/import-labs.ts
https://proyectos.andes.gob.ar/browse/LAB-5
1. 
2. 
3.
=> LAB: remover condicion cdas heller

facturacion/services/prestaciones.service.ts
Facturacion: soluciona error en respuesta de la api, fallaba para las prestaciones que no tenian turno (fuera de agenda).
1. 
2. 
3.
=> Facturacion: soluciona error en respuesta de la api

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/recupero-financiero/query-recupero.ts
https://proyectos.andes.gob.ar/browse/MISC-169
1. Se modifica la forma de obtener el idTipoNomenclador por medio un procedimiento de SIPS.
2. Se agrega la facturación para prepagas, que se había perdido hace tiempo.
3.
=> Facturación: fix obtener idTipoNomenclador - facturación prepagas

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts, cda-laboratorios/logger/msCDALaboratorios.ts, package.json
=> logs ms cda labs

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts
=> cda logs paciente

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts, cda-laboratorios/index.ts
=> remove logs info

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/index.ts
=> log datos paciente

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/index.ts
=> remove logs paciente

cda-laboratorios/controller/operations.ts
=> logs datos encabezado

cda-laboratorios/controller/operations.ts
=> remove logs datos encabezado

cda-laboratorio-central/index.ts
=> CDA-LABS remove queue

cda-laboratorio-central/index.ts, cda-laboratorios/index.ts
=> CDA-LABS remove queue labs

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts
Logear usuario y queries en caso de error en select a base de datos del SIPS
1. 
2. 
3.
=> CDA Labs log query error

cda-laboratorio-central/controller/import-labs.ts, cda-laboratorio-central/controller/operations.ts, cda-laboratorio-central/logger/msCDALaboratorioCentral.ts, cda-laboratorios/index.ts
Logs de laboratorio central en coleccion propia.
Actualización de los para incluir datos de paciente
1. 
2. 
3.
=> CDA Labs Central logger

cda-laboratorio-central/controller/import-labs.ts
=> fix date cda lab central

cda-laboratorio-central/controller/operations.ts
=> cda: ignorar log prestacion existente

cda-laboratorio-central/controller/operations.ts
1. Incluir payload en log de error de Post
2. 
3.
=> CDA LabCentral log payload

facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/recupero-financiero/query-recupero.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/facturar/sumar/query-sumar.ts, facturacion/index.ts
=> Facturacion: se corrige log en facturacion

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/index.ts
Se agrega facturacion prepagas y OS desde buscador de turno.
1. Se agregan logs para registrar aquellas prestaciones que no se encuentren configuradas.
2. Se realizan cambios para poder facturar recupero desde el buscador de turnos.
3.
=> Facturacion: Se agrega prepagas y OS desde buscador de turno

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts, cda-laboratorios/index.ts, cda-laboratorios/package.json, cda-laboratorios/utils/informes/informe-body.ts, cda-laboratorios/utils/informes/informe-footer.ts, cda-laboratorios/utils/informes/informe-header.ts, cda-laboratorios/utils/informes/informe-lab.ts, cda-laboratorios/utils/model/html-component.class.ts, cda-laboratorios/utils/model/informe.class.ts, cda-laboratorios/utils/sass/main.scss
Reemplazar service de andes por generación de PDF dentro del microservicio
1. 
2. 
3.
=> CDA_Laboratorios: refactor-pdf

cda-laboratorios/index.ts
=> clean code

cda-nomivac/controller/sisa.ts, cda-nomivac/logger/nomivacCDALog.ts, cda-nomivac/package-lock.json, cda-nomivac/package.json, cda-nomivac/service/nomivacCDA.ts
https://proyectos.andes.gob.ar/browse/VAC-122
1. Se actualizan logs del MS CDANomivac por Logger.
2. 
3.
=> CDANomivac: se cambian logs por Logger

facturacion/configJson/configJson.ts, facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/recupero-financiero/query-recupero.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/index.ts, facturacion/logger/msFacturacion.ts, facturacion/package-lock.json, facturacion/package.json
https://proyectos.andes.gob.ar/browse/MISC-212
Se actualizan los logs del MS Facturación
1. Se cambian logs por Logger.
2. Se agregan controles para evitar doble logueo en algunos errores.
3.
=> Facturacion: se actualiza log con Logger

lamp/controller/lamp.controller.ts, lamp/index.ts, lamp/logger/lampLog.ts, lamp/service/lamp.service.ts
https://proyectos.andes.gob.ar/browse/EP-169
1. Logea errores en  colección `msLogs` usando logger propio del servicio.
2. 
3.
=> LAMP: nueva colección log lamp

cda-nomivac/service/nomivacCDA.ts
=> nomivac fix log

facturacion/facturar/sumar/query-sumar.ts, facturacion/index.ts
facturacion:
- refactor de logs en queries-sumar
- limpia funcion saveBeneficiario que ya no se usa mas
1. 
2. 
3.
=> facturacion: refactor logs

cda-heller/controller/ejecutaCDA.ts, cda-heller/index.ts, cda-heller/logger/msCDAHeller.ts, cda-heller/package.json
Refactor logs cda heller
1. 
2. 
3.
=> CDA HELLER: logs

cda-laboratorio-central/index.ts, cda-laboratorios/controller/import-labs.ts, cda-laboratorios/index.ts
MS CDAs filtran documentos vacios
1. 
2. 
3.
=> cdas: filtrar documentos vacios

cda-laboratorio-central/controller/operations.ts
=> cda lab central: disable post log

profesional_sisa/index.ts, profesional_sisa/logger/msProfesionalSISA.ts, profesional_sisa/package.json, profesional_sisa/service/operaciones.service.ts
=> PROF_SISA: logs para ms prof sisa

profesional_sips/controller/consultas.ts, profesional_sips/controller/ejecutaConsulta.ts, profesional_sips/service/operaciones.service.ts
https://proyectos.andes.gob.ar/browse/MISC-198
1. Se corrige error al insertar profesional sips que se encontraban inactivos
2. Se agrega consulta a Sips sobre idEfector por error visto en  logs
3. Se agrega controles varios
=> Profesional_sips: corrige error al crear profesional en sips

facturacion/configJson/datos-reportables.ts, facturacion/facturar/sumar/factura-sumar.ts, facturacion/facturar/sumar/query-sumar.ts
1. Se corrige la generación de datos reportables, ya que algunas veces se duplicaban 
2. Se actualiza el código
3.
=> Facturacion: Corrige errores en datos reportables sumar

facturacion/index.ts
https://proyectos.andes.gob.ar/browse/MISC-242
1. Se cambía de pool global de conexiones a pool reservado, para evitar cierre de conexión en caso de concurrencia de requests
2. Se agrega control para evitar que queden conexiones abiertas en caso de excepciones no manejadas.
=> FAC: control de concurrencia y cierre de conexiones

facturacion/configJson/configJson.ts, facturacion/facturar/dto-facturacion.ts, facturacion/facturar/recupero-financiero/factura-recupero.ts, facturacion/facturar/recupero-financiero/query-recupero.ts, facturacion/interfaces/IDtoRecupero.ts
https://proyectos.andes.gob.ar/browse/MISC-231
1. 
2. 
3.
=> FAC: update relPacienteObraSocial

facturacion-perinatal/index.ts
No está encontrando para prestaciones (distintas a las de control embarazo) registros que incluyan alguna de estas.
1. 
2. 
3.
=> facturacion-perinatal(fix): corrige busqueda de conceptos en registros

facturacion/configJson/configJson.ts, facturacion/factura.ts, facturacion/facturar/recupero-financiero/query-recupero.ts, facturacion/index.ts
https://proyectos.andes.gob.ar/browse/MISC-244
1. 
2. 
3.
=> FAC: query recupero refactor

appGestion/controller/recuperaDatos.ts
En el microservicio de APP-GESTION se agrega un filtro en la consulta de personal de salud.
1. 
2. 
3.
=> fix(app-Gestion): Se agrega filtro en consulta de personal de salud

cda-laboratorios/controller/import-labs.ts, cda-laboratorios/controller/operations.ts, cda-laboratorios/index.ts
https://proyectos.andes.gob.ar/browse/MISC-252
GLPI: https://glpi.andes.gob.ar/front/ticket.form.php?id=3187
1.  Se utiliza el paciente de la tabla SIPS.dbo.Sys_Paciente y no el de la tabla LAB_ResultadoEncabezado para realizar el matching.
2. La búsqueda en la tabla LAB_ResultadoEncabezado se realiza por documento y sexo (antes sólo documento).
3. Loguear los casos que no superaron el matching, para ver la diferencia entre pacientes y poder revisar desde los logs para estos problemas, que se reportan en glpi.
4. Se agrea mapeo entre sexo Indefinido Sips y otro de MPI.
=> cda-laboratorios: se modifica control matching entre paciente Sips y Andes

facturacion-perinatal/controller/perinatal.ts, facturacion-perinatal/index.ts, sip-plus-perinatal/controller/sip-plus.ts
[PER-72](https://proyectos.andes.gob.ar/browse/PER-72) - Molécula "embarazo" agregar numero
1. Se agrega chequeo que permite agregar un valor numerico para cuando se selecciona mas de 10 embarazos
2. 
3.
=> PERINATAL - Agregar ingreso numérico para mas de 10 embarazos

paciente_heller/index.ts, paciente_heller/package-lock.json, paciente_heller/package.json
https://proyectos.andes.gob.ar/secure/Dashboard.jspa
1. Se actualizaron los package_lock y se modificaron las condiciones de los find de create y update de paciente_heller
2. 
3.
=> MISC - Paciente heller MS

bi-queries/controller/pipeline-builder.ts
Agrega control por organización origen
1. 
2. 
3.
=> fix(BIQUERIES): Agrega control por parametro organización

cda-laboratorio-central/controller/operations.ts, cda-laboratorios/controller/operations.ts, package.json, profesional_sisa/controller/ejecutaConsulta.ts, profesional_sisa/index.ts, profesional_sisa/logger/msProfesionalSISA.ts, profesional_sisa/package-lock.json, profesional_sisa/package.json, profesional_sisa/service/operaciones.service.ts
Se cambia node-fecth por got para realizar requests
1. 
2. 
3.
=> PROF SISA: got request

profesional_sisa/service/requestHandler.ts
Agregar archivo de request faltante
=> fix(PROF): Agregar archivo de request faltante

profesional_sisa/service/operaciones.service.ts
Se agrega la búsqueda en API - ANDES de: Profesión de referencia y entidad formadora. Esto es porque en los datos del profesional no quedan guardados los códigos de sisa de estos datos
1. 
2. 
3.
=> fix(PROF): Agrega búsqueda de campos en API

profesional_sisa/service/operaciones.service.ts
Agrega control de teléfono vacío para migrar a sisa
=> fix(PROF): Agrega control de teléfono vacío

cda-validator/index.ts, cda-validator/logger/msCDAValidator.ts, cda-validator/service/organizaciones.service.ts
Separación de logs de guarida y ambulatorio
Se agrega límite de tiempo expiredAt
1. 
2. 
3. 
- [ X] No corresponde
=> cda-validator: se agregan y corrigen logs en cda-validator

cda-validator/controller/ejecutaCDA.ts, cda-validator/controller/ejecutaCDAGuardia.ts, cda-validator/controller/import-cdaValidators.ts, cda-validator/index.ts
Se agregan controle y se modifican/quitan logs.
1. Se agregan controles por errores logueados
2. Se modifican/quitan logs generales, ya que cuando algún SIPS hospitalario está caído se loguean estos casos constantemente.
3.
=> fix(cda-validator): se quitan algunos logs

cda-validator/utils/model/informeCDA.class.ts
Se modifica el uso de las variables del servidor porque no consideraba cwd, por lo que se creó una nueva llamada CDA_PATH
1. 
2. 
3.
=> fix(cda-validator): cambia nombre variable de entorno por archivos

notificaciones/config.private.example.ts, notificaciones/controller/notificaciones.ts, notificaciones/index.ts, notificaciones/logger/notificacionesLog.ts, notificaciones/package.json
https://proyectos.andes.gob.ar/browse/MISC-345
1. Rutas y controlador p/Api's de Whatsapp
2. Waapi
3.
=> MS - APIs Whatsapp

notificaciones/index.ts
=> fix(Notificaciones): cambia el res en el index

notificaciones/controller/notificaciones.ts, notificaciones/schemas/schemas.ts
https://proyectos.andes.gob.ar/browse/MISC-353
1.  Chequeo por numero de teléfono.
2.  Chequear logs por errores (por conexión a la base)
3.  Agregar un logs en caso de éxito
4.  Agregar el espacio físico de la agenda 
5.  Sacar el "profesional no asignado"
6.  Si tiene "alias" mostrar en lugar de nombre.
=> MISC: Cambios en el Microservicio de notificaciones

notificaciones/controller/notificaciones.ts
Corrigen datos y casos logueados 
1. 
2. 
3.
=> notificaciones: se corrige logueo de datos

notificaciones/controller/notificaciones.ts
Se elimina control por prestación y se quitan variables globales
1. 
2. 
3.
=> Notificaciones: quita control por prestación

notificaciones/controller/notificaciones.ts
[https://proyectos.andes.gob.ar/browse/MISC-354](https://proyectos.andes.gob.ar/browse/MISC-354)
1. Cambia la funcionalidad en send-message para que el objetivo sea solo enviar el mensaje. Se quitan los controles por turnos y se los lleva a la API 
Agregar en constantes el mensaje para la cancelación del turno:
{
"_id" : ObjectId("66996af1f1b15d16a772d67d"),
"key" : "turno-suspencion",
"nombre" : "Sr/a. *#nombrePaciente#*\n\nSu turno para *#tipoPrestacion#*, el día *#fecha#*, #profesional# en #organizacion# *ha sido CANCELADO*.\n\n Este WhatsApp no admite respuestas. Es usado por el Ministerio de Salud de Neuquén para recordatorios de turnos. Para más información, diríjase al Centro de Salud u Hospital más cercano. \nTeléfono oficial del Ministerio de Salud de Neuquén.  \n\nMuchas …
=> Notificacion: cambia el objetivo del MS de notificacion

cda-validator/controller/import-cdaValidators.ts, cda-validator/index.ts, cda-validator/service/organizaciones.service.ts
Se diferencia ambito en log de getOrganización
1. 
2. 
3.
=> cda-validator: se separan logs en getOrganizacion

cda-validator/index.ts
Se elimina log innecesario que ensucia la bd
1. 
2. 
3.
=> fix(Guardia): quita logs innecesario

notificaciones/controller/notificaciones.ts
https://proyectos.andes.gob.ar/browse/CIT-321
Microservices y script Recordatorio: Revisar function replaceTemplate(template, variables)
Si la etiqueta está vacía devuelve la etiqueta, Ej: #profesional#
Si la agenda tiene un solo profesional, en el mensaje decir: con el/la profesional ...
Si la agenda tiene mas de un profesional, en el mensaje decir: con los profesionales ....
=> CIT - Notificaciones: muestra etiqueta vacía #profesional#

notificaciones/controller/notificaciones.ts, notificaciones/index.ts
https://proyectos.andes.gob.ar/browse/CIT-361
1.  Se habilitan 3 instancias de notificaciones p/whatsapp.
2.  Se usan en forma  rtotativa según terminación del nro de Tel.
3.
=> CIT - Instancias notificaciones (rotativas)

cda-guardia-heller/controller/ejecutaCDA.ts, cda-guardia-heller/controller/verificaCDA.ts, cda-guardia-heller/index.ts, cda-guardia-heller/logger/msCDAGuardiaHeller.ts, cda-guardia-heller/logger/msCDAValidator.ts, cda-guardia-heller/package-lock.json, cda-guardia-heller/package.json, cda-guardia-heller/schemas/guardia.ts, cda-guardia-heller/services/cda.service.ts, cda-guardia-heller/services/paciente.ts, cda-guardia-heller/tsconfig.json
https://proyectos.andes.gob.ar/browse/MISC-344
1. Nuevo microservicio **cda-guardia-heller** req: **http://localhost:3000/cda/guardia**
2. Enviar **token** en el request.
3. Guarda el CDA a travez de API con los datos recibidos en el request.
4. Response OK retorna { "cda": "xxxxxxxxxxxxxx", "paciente": "pppppppppppp"}
5. En colección authApps agregar permisos **mpi: paciente:*** y generar token.
- [X ] Si
- [] No
=> CDA-Guardia Heller

bi-queries/index.ts, bi-queries/schemas/query.ts
https://proyectos.andes.gob.ar/browse/BI-140
1.  Se modificó esquema 'QuerySchema' se gregó atributo: inactiva: { estado: Boolean, fecha: Date, motivo: String }
2.  En index.js, se modificó ruta 'get('/queries')', se agregó filtro para que no liste inactivas.
=> BI - No consultar query inactiva

cda-validator/constantes.ts, cda-validator/index.ts
1. Agrega control en errores cuando la conexión de algún sql está caído para el ámbito ambulatorio.
2. Pasa el array de constantes al config.private (en prod chequear efectores y sus conexiones vigentes)
3.
=> cda-validator: control en errores de conexión ámbito ambulatorio

cda-laboratorios/controller/operations.ts
1. Se filtran de la migración de cdas de laboratorios aquellos efectores que están incorporados al sil multiefector (SIL2)
2. 
3. 
Agregar al config.private la variable idEfectoresSIL2 con un array de id de efectores a ignorar en la migración
```
export const idEfectoresSIL2 = [100];
```
=> fix(cda-laboratorio): se quita la migración para efectores del SIL2

notificaciones/controller/notificaciones.ts, notificaciones/logger/notificacionesLog.ts
https://proyectos.andes.gob.ar/browse/MISC-361
1.  Se agrega en el log del microservicio de notificaciones el ID de turno y el ID de paciente.
=> MISC - Agregar data en el log info de notificaciones
